---
# Setup/install tasks.
- name: Install MySQL
  include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: install
# Configure MySQL.
- name: Config MySQL
  include: secure-installation.yml
  tags: config

- name: Config Replication
  include: replication.yml
  tags: config-rep