---
# tasks file for ansible-openstack-mariadb
- name: Add Mariadb repo
  yum_repository:
    name: "{{ galera_repo.name }}"
    description: "{{ galera_repo.description }}"
    baseurl: "{{ galera_repo.baseurl }}"
    gpgkey: "{{ galera_repo.gpgkey | default(omit) }}"
    gpgcheck: yes
    enabled: yes
  register: add_repos
  until: add_repos is success
  retries: 5
  delay: 2

- name: Install mariadb packages
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - mariadb 
    - mariadb-server 
    - python2-PyMySQL
    - MySQL-python
  register: install_package
  until: install_package is success
  retries: 5
  delay: 2

- name: remove mailformed ip address
  lineinfile:
    regexp: (?<!{{ hostvars[item].ansible_host }})\s+{{ item }}
    state: absent
    dest: "/etc/hosts"
  with_items: "{{ groups['databases'] }}"
  become: true

- name: remove mailformed hostname
  lineinfile:
    regexp: '^{{ hostvars[item].ansible_host }}\s+(?!{{ item }})'
    state: absent
    dest: "/etc/hosts"
  with_items: "{{ groups['databases'] }}"
  become: true

- name: add appropriate ip <=> hostname mapping
  lineinfile:
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    dest: "/etc/hosts"
  with_items: "{{ groups['databases'] }}"
  become: true

- name: Creates directory
  file:
    path: /data/log/{{item}}
    state: directory
    owner: mysql
    group: mysql
    mode: 0775
  with_items:
    - mysql
    - mysqld
    - mysqld/tmpdir/
  register: create_directory
  until: create_directory is success
  retries: 5
  delay: 2

# - name: Creates directory /data/lib/mysql
#   file:
#     path: /data/lib/mysql
#     state: directory
#     owner: mysql
#     group: mysql
#     mode: 0775
#   register: create_directory
#   until: create_directory is success
#   retries: 5
#   delay: 2

- name: Copying config mariadb
  template:
    src: server.cnf.j2
    dest: /etc/my.cnf.d/server.cnf

# This command will exit non-zero when the root password was set previously
- name: Check if root password is unset
  shell: >
    mysql -u root
    -p'{{ mariadb_root_password }}'
    -h localhost
    -S {{ mariadb_socket }}
    -e "quit"
  changed_when: false
  ignore_errors: true
  register: root_pwd_check

# Repeat runs with the same password can continue idempotently, otherwise fail.
- name: Check if the specified root password is already set
  shell: >
    mysqladmin -u root status
  changed_when: false
  when: root_pwd_check.rc != 0
  
- name: Set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: localhost
    login_unix_socket: "{{ mariadb_socket }}"
    state: present
  when: root_pwd_check.rc != 0

- name: Set MariaDB root password for 127.0.0.1, ::1, FQDN
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ mariadb_socket }}"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
  when: root_pwd_check.rc != 0

- name: Copying /root/.my.cnf config
  template:
    src: root-my.cnf.j2
    dest: /root/.my.cnf

- name: Ensure mariabd started and enabled
  systemd:
    name: mariadb
    state: started
    enabled: true
